### ISSUE TITLE
Subdirectory with recursive: false will still recurse

### ISSUE THREAD

**Issue by villermen** [villermen/web-file-browser#7]
```yaml
    directories:
        /:
            display:
                webpages: true
                directories: true
                files: true
            recursive: true
        asdf/foo:
            blacklist:
                all:
                - genericblacklist2
            recursive: false
```

This would still allow `asdf/foo/bar` to be viewed. Directories without a configuration must have a configured parent that says recursive, without a child that inverts that.
